apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - env:
        - name: MONGODB_DBNAME
          value: "vote"
        imagePullPolicy: IfNotPresent
        image: mongo
        name: mongo
        ports:
        - containerPort: 27017
